version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: "daily"
    time: "04:42"
  assignees:
  - pfichtner
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:42"
  assignees:
  - pfichtner
  ignore:
    - dependency-name: "org.junit:junit-bom"
      versions: [">=6.0.0"]

    - dependency-name: "com.pi4j:pi4j-core"
      versions: [">=3.0.0"]

    - dependency-name: "org.apache.camel:*"
      versions: [">=4.0.0"]

    - dependency-name: "nl.jqno.equalsverifier:equalsverifier"
      versions: [">=4.0.0"]

    - dependency-name: "io.rest-assured:rest-assured"
      versions: [">=6.0.0"]

